[package]
name = "uwuifier"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = "0.19.0"
rand = "*"
lazy_static = "*"

[dependencies.xxhash-rust]
version = "*"
features = ["xxh3", "const_xxh3"]

[profile.release]
opt-level = 3
lto = true
strip = true 
incremental = true